import { tableMapperValues } from "@skeletonlabs/skeleton";
import type { TableSource } from '@skeletonlabs/skeleton';

const mensgames = [
	{
    g: '01',
    d: 'wed, jul 06',
		t: '10:00 PM',
		t1: 'beaver dam',
    t1c: 'beaverdam',
    t1s: '10',
    t2: 'tvshkahomma',
    t2c: 'tvshkahomma',
    t2s: '3',
	},
	{
		g: '02',
    d: 'wed, jul 06',
		t: '10:00 PM',
		t1: 'beaver dam',
    t1c: 'beaverdam',
    t1s: '10',
    t2: 'tvshkahomma',
    t2c: 'tvshkahomma',
    t2s: '3',
	},
	{
		g: '03',
    d: 'wed, jul 06',
		t: '10:00 PM',
		t1: 'beaver dam',
    t1c: 'beaverdam',
    t1s: '10',
    t2: 'tvshkahomma',
    t2c: 'tvshkahomma',
    t2s: '3',
	},
	{
		g: '04',
    d: 'wed, jul 06',
		t: '10:00 PM',
		t1: 'beaver dam',
    t1c: 'beaverdam',
    t1s: '10',
    t2: 'tvshkahomma',
    t2c: 'tvshkahomma',
    t2s: '3',
	},
	{
		g: '05',
    d: 'wed, jul 06',
		t: '10:00 PM',
		t1: 'beaver dam',
    t1c: 'beaverdam',
    t1s: '10',
    t2: 'tvshkahomma',
    t2c: 'tvshkahomma',
    t2s: '3',
	},
  {
		g: '06',
    d: 'wed, jul 06',
		t: '10:00 PM',
		t1: 'beaver dam',
    t1c: 'beaverdam',
    t1s: '10',
    t2: 'tvshkahomma',
    t2c: 'tvshkahomma',
    t2s: '3',
	},
	{
		g: '07',
    d: 'wed, jul 06',
		t: '10:00 PM',
		t1: 'beaver dam',
    t1c: 'beaverdam',
    t1s: '10',
    t2: 'tvshkahomma',
    t2c: 'tvshkahomma',
    t2s: '3',
	},
	{
		g: '08',
    d: 'wed, jul 06',
		t: '10:00 PM',
		t1: 'beaver dam',
    t1c: 'beaverdam',
    t1s: '10',
    t2: 'tvshkahomma',
    t2c: 'tvshkahomma',
    t2s: '3',
	},
	{
		g: '09',
    d: 'wed, jul 06',
		t: '10:00 PM',
		t1: 'beaver dam',
    t1c: 'beaverdam',
    t1s: '10',
    t2: 'tvshkahomma',
    t2c: 'tvshkahomma',
    t2s: '3',
	}
];

export const mensTable: TableSource = {
  // A list of heading labels.
  head: ['Game', 'Date', 'Time', 'Team 1', 'Team 1 Score', 'Team 2', 'Team 2 Score'],
  // The data visibly shown in your table body UI.
  body: tableMapperValues(mensgames, ['g', 'd', 't', 't1', 't1s', 't2', 't2s']),
};
